### ISSUE TITLE
Error in inotifywait.sh

### ISSUE THREAD

**Issue by Benoit485** [devodev/docker-inotify#1]
Hello

Thanks for this script

You have an error in inotifywait.sh script, in line 20 :

INOTIFY_CFG_EVENTS="${INOTIFY_CFG_EVENT:-"modify delete delete_self"}"

in second INOTIFY_CFG_EVENT your forgot S

**Comment by devodev** [comment]
Thanks will try to send a fix soon!

**Comment by devodev** [comment]
Released new image version v0.1.1 with fix: https://github.com/devodev/docker-inotify/pull/3
