### ISSUE TITLE
Potential race condition if multiple event are issued at once

### ISSUE THREAD

**Issue by dud225** [devodev/docker-inotify#4]
Hello

I'm wondering what would happen if multiple events come up at once.

When looking at the current code:
```bash
while true; do
   [...]
    events=$(watch)
    [....]
    "${SCRIPT}" ${events}
```
I believe that the second event would be lost as it would appear while the script is running.

I would suggest to consider this kind of implementation:
```bash
while events=$(watch); do
  "${SCRIPT}" ${events}
done
```

**Comment by devodev** [comment]
Thank you, I agree.
I merged this today #5 which should fix this.
Will push a new image soon.
